<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <ImplicitUsings>false</ImplicitUsings>
    <Nullable>disable</Nullable>
    <AssemblyName>ShikiPad</AssemblyName>
    <ApplicationManifest>assets\ShikiPad.manifest</ApplicationManifest>
    <ApplicationIcon>assets\shiki.ico</ApplicationIcon>
    <PlatformTarget>x64</PlatformTarget>
    <Version>5.2.0</Version>
    <AssemblyVersion>5.2.0.0</AssemblyVersion>
    <FileVersion>5.2.0.0</FileVersion>
    <InformationalVersion>5.2.0</InformationalVersion>
    <IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="src\*.cs" />
  </ItemGroup>
</Project>
